const palette = {
  orange: "#FF6B35",
  orangeLight: "#FF8C5A",
  amber: "#FFA033",
  cream: "#F5E6D0",
  brown: "#8B5E3C",
  darkBrown: "#4A3728",
  charcoal: "#1A1A1A",
  darkSurface: "#242424",
  darkCard: "#2E2E2E",
  darkBorder: "#3A3A3A",
  white: "#FFFFFF",
  offWhite: "#F8F8F8",
  lightSurface: "#FAFAFA",
  lightCard: "#FFFFFF",
  lightBorder: "#EBEBEB",
  sepiaBg: "#F4ECD8",
  sepiaCard: "#EDE3D0",
  sepiaText: "#3B2A1A",
  sepiaAccent: "#8B6914",
  textLight: "#666666",
  textMuted: "#999999",
  success: "#34C759",
  error: "#FF3B30",
  blue: "#007AFF",
  downloading: "#0A84FF",
};

export type Theme = "dark" | "light" | "sepia" | "amoled" | "warm" | "slate";

export const ThemeColors = {
  dark: {
    background: "#0A0E1A",
    surface: "#111624",
    card: "#151C2A",
    border: "#1F2636",
    text: "#E8EDFF",
    textSecondary: "#9AA4C4",
    textMuted: "#5C6680",
    accent: "#FF6B35",
    accentLight: "#FF8C5A",
    tabBar: "#111624",
    icon: "#9AA4C4",
    iconActive: "#FF6B35",
    error: palette.error,
  },
  light: {
    background: palette.offWhite,
    surface: palette.lightSurface,
    card: palette.lightCard,
    border: palette.lightBorder,
    text: "#1A1A1A",
    textSecondary: "#555555",
    textMuted: "#999999",
    accent: palette.orange,
    accentLight: palette.orangeLight,
    tabBar: palette.white,
    icon: "#888888",
    iconActive: palette.orange,
    error: palette.error,
  },
  sepia: {
    background: palette.sepiaBg,
    surface: palette.sepiaCard,
    card: palette.sepiaCard,
    border: "#D4C5A9",
    text: palette.sepiaText,
    textSecondary: "#6B5240",
    textMuted: "#9E8775",
    accent: palette.sepiaAccent,
    accentLight: "#B88B2A",
    tabBar: palette.sepiaCard,
    icon: "#8B7355",
    iconActive: palette.sepiaAccent,
    error: palette.error,
  },
  // NEW THEMES START HERE
  amoled: {
    background: "#000000", // Pure black for AMOLED
    surface: "#0A0A0A",
    card: "#0F0F0F",
    border: "#1A1A1A",
    text: "#FFFFFF",
    textSecondary: "#B0B0B0",
    textMuted: "#707070",
    accent: "#00E5FF", // Cyan accent for AMOLED
    accentLight: "#33EBFF",
    tabBar: "#000000",
    icon: "#B0B0B0",
    iconActive: "#00E5FF",
    error: palette.error,
  },
  warm: {
    background: "#1A1008",
    surface: "#221508",
    card: "#2A1C0F",
    border: "#3D2A15",
    text: "#FFE8CC",
    textSecondary: "#C4956A",
    textMuted: "#7A5535",
    accent: "#FF8C42",
    accentLight: "#FFA96A",
    tabBar: "#221508",
    icon: "#C4956A",
    iconActive: "#FF8C42",
    error: palette.error,
  },
  slate: {
    background: "#1E2430",
    surface: "#252D3D",
    card: "#2C3548",
    border: "#3A4560",
    text: "#D4DAEA",
    textSecondary: "#8A97B0",
    textMuted: "#556070",
    accent: "#7EB8D4",
    accentLight: "#A2CCE0",
    tabBar: "#252D3D",
    icon: "#8A97B0",
    iconActive: "#7EB8D4",
    error: palette.error,
  },
};

export default {
  orange: palette.orange,
  orangeLight: palette.orangeLight,
  amber: palette.amber,
  success: palette.success,
  error: palette.error,
  blue: palette.blue,
  downloading: palette.downloading,
};
